export const STORE_SIGNIN_GOOGLE_DATA = "STORE_SIGNIN_GOOGLE_DATA";
export const STORE_USER_DATA = "STORE_USER_DATA";
export const SIGNIN_FAILED = "SIGNIN_FAILED";
export const SHOW_LOADER_AUTH = "SHOW_LOADER_AUTH";
export const MENU_DATA = "MENU_DATA";
